


project_DIRECTORY := ~/Git/MQTT-Scheduler
working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/hellow_world
project_LIB := ~/Git/MQTT-Scheduler/lib
program_NAME := hellow 

include ~/Git/MQTT-Scheduler/mastermake/Makefile