ifndef t
$(error target for make not set)
endif

working_DIRECTORY:=~/Git/MQTT-Scheduler/tests/hellow world
program_NAME:=hellow 
target_MACHINE:=$t
bone_BIN_DIR:=/usr/local/sbin

include ~/Git/MQTT-Scheduler/mastermake/Makefile